# Generated by Django 5.1.15 on 2026-09-12 05:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'واحد شمارش',
                'verbose_name_plural': 'واحدهای شمارش',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='inventory.category')),
            ],
            options={
                'verbose_name': 'دسته کالا',
                'verbose_name_plural': 'دسته\u200cهای کالا',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=32, unique=True)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('pack_size', models.PositiveIntegerField(default=1)),
                ('weight_grams', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('reorder_point', models.PositiveIntegerField(default=0)),
                ('has_expiry', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.category')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.unitofmeasure')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالاها',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='StockDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('entry', 'ورود'), ('exit', 'خروج'), ('transfer', 'انتقال'), ('count', 'انبارگردانی'), ('adjust', 'اصلاح')], max_length=16)),
                ('number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('posted', 'ثبت\u200cشده'), ('cancelled', 'باطل')], default='draft', max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_docs', to=settings.AUTH_USER_MODEL)),
                ('dest_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dest_docs', to='organization.warehouse')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_stock_docs', to=settings.AUTH_USER_MODEL)),
                ('source_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_docs', to='organization.warehouse')),
            ],
            options={
                'verbose_name': 'سند انبار',
                'verbose_name_plural': 'اسناد انبار',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockDocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockdocument')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
            options={
                'verbose_name': 'ردیف سند',
                'verbose_name_plural': 'ردیف\u200cهای سند',
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('in', 'ورود'), ('out', 'خروج'), ('transfer_out', 'انتقال-خروج'), ('transfer_in', 'انتقال-ورود'), ('adjust', 'اصلاح'), ('count', 'انبارگردانی')], max_length=16)),
                ('qty', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('reference', models.CharField(blank=True, default='', max_length=64)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_txns', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.warehouse')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.product')),
            ],
            options={
                'verbose_name': 'تراکنش موجودی',
                'verbose_name_plural': 'تراکنش\u200cهای موجودی',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'warehouse', '-created_at'], name='inventory_i_product_6a2fff_idx'), models.Index(fields=['type', '-created_at'], name='inventory_i_type_afd258_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('invoice_ref', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('active', 'فعال'), ('converted', 'تبدیل\u200cشده به خروج'), ('released', 'آزادشده'), ('expired', 'منقضی\u200cشده')], db_index=True, default='active', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.warehouse')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.product')),
            ],
            options={
                'verbose_name': 'رزرو موجودی',
                'verbose_name_plural': 'رزروهای موجودی',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'warehouse', 'status'], name='inventory_i_product_003335_idx'), models.Index(fields=['status', 'expires_at'], name='inventory_i_status_6d8892_idx')],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_qty', models.IntegerField(default=0)),
                ('reserved_qty', models.IntegerField(default=0)),
                ('in_transit_qty', models.IntegerField(default=0)),
                ('avg_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_rows', to='organization.warehouse')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_rows', to='inventory.product')),
            ],
            options={
                'verbose_name': 'موجودی',
                'verbose_name_plural': 'موجودی\u200cها',
                'ordering': ['warehouse', 'product'],
                'unique_together': {('product', 'warehouse')},
            },
        ),
    ]
