# Generated by Django 5.1.15 on 2026-09-12 17:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=80, unique=True)),
                ('entity', models.CharField(max_length=80)),
                ('operation', models.CharField(max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('client_updated_at', models.DateTimeField(blank=True, null=True)),
                ('server_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('applied', 'اعمال\u200cشده'), ('conflict', 'تعارض'), ('failed', 'ناموفق')], default='pending', max_length=12)),
                ('error', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['server_updated_at'],
            },
        ),
    ]
