# Generated by Django 5.1.15 on 2026-09-12 16:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0002_alter_invoice_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('type', models.CharField(choices=[('asset', 'دارایی'), ('liability', 'بدهی'), ('equity', 'سرمایه'), ('revenue', 'درآمد'), ('expense', 'هزینه')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='finance.account')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True)),
                ('entry_date', models.DateField(default=django.utils.timezone.localdate)),
                ('description', models.TextField(blank=True, default='')),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('posted', 'ثبت\u200cشده'), ('void', 'باطل\u200cشده')], default='draft', max_length=12)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('debit', models.DecimalField(decimal_places=0, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('credit', models.DecimalField(decimal_places=0, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='finance.account')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.journalentry')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=16, validators=[django.core.validators.MinValueValidator(1)])),
                ('method', models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارت'), ('transfer', 'واریز'), ('cheque', 'چک')], max_length=16)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('note', models.TextField(blank=True, default='')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='sales.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_receipts', to='sales.invoice')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, unique=True)),
                ('direction', models.CharField(choices=[('received', 'دریافتی'), ('issued', 'پرداختی')], max_length=12)),
                ('bank', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=160)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=16, validators=[django.core.validators.MinValueValidator(1)])),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('registered', 'ثبت\u200cشده'), ('deposited', 'در انتظار وصول'), ('cleared', 'وصول\u200cشده'), ('bounced', 'برگشتی'), ('cancelled', 'لغوشده')], default='registered', max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='finance.receipt')),
            ],
        ),
    ]
