# Generated by Django 5.1.15 on 2026-09-12 17:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('hr', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7)),
                ('basis_amount', models.DecimalField(decimal_places=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('paid', 'پرداخت\u200cشده')], default='draft', max_length=12)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True)),
                ('document_type', models.CharField(choices=[('income', 'درآمد'), ('expense', 'هزینه')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=16, validators=[django.core.validators.MinValueValidator(1)])),
                ('document_date', models.DateField(default=django.utils.timezone.localdate)),
                ('description', models.TextField(blank=True, default='')),
                ('is_void', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_documents', to='finance.account')),
                ('cash_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_documents', to='finance.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_document', to='finance.journalentry')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='YYYY-MM', max_length=7)),
                ('base_salary', models.DecimalField(decimal_places=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('overtime', models.DecimalField(decimal_places=0, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('bonus', models.DecimalField(decimal_places=0, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('deductions', models.DecimalField(decimal_places=0, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('net_amount', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('paid', 'پرداخت\u200cشده')], default='draft', max_length=12)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7)),
                ('target_amount', models.DecimalField(decimal_places=0, max_digits=16, validators=[django.core.validators.MinValueValidator(1)])),
                ('achieved_amount', models.DecimalField(decimal_places=0, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_targets', to='organization.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_targets', to='hr.employee')),
            ],
        ),
    ]
