# Generated by Django 5.1.15 on 2026-09-12 15:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('sales', '0002_alter_invoice_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='pending', max_length=24)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_stop', to='sales.invoice')),
            ],
            options={
                'ordering': ['trip', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('delivered', 'تحویل کامل'), ('partial', 'تحویل ناقص'), ('failed', 'عدم تحویل'), ('returned', 'برگشت')], max_length=16)),
                ('reason', models.CharField(blank=True, choices=[('closed', 'مشتری بسته بود'), ('no_cash', 'عدم موجودی وجه'), ('mismatch', 'مغایرت سفارش'), ('refused', 'عدم پذیرش'), ('wrong_address', 'آدرس اشتباه'), ('absent', 'مشتری در محل نبود'), ('damaged', 'کالا آسیب دیده'), ('other', 'سایر')], default='', max_length=32)),
                ('delivered_qty', models.JSONField(blank=True, default=dict)),
                ('received_amount', models.DecimalField(decimal_places=0, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_method', models.CharField(blank=True, default='', max_length=16)),
                ('customer_signature_url', models.URLField(blank=True, default='')),
                ('receipt_photo_url', models.URLField(blank=True, default='')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='delivery.deliverystop')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('planned', 'برنامه\u200cریزی\u200cشده'), ('loading', 'در حال بارگیری'), ('out_for_delivery', 'در مسیر'), ('completed', 'تکمیل\u200cشده'), ('cancelled', 'لغوشده')], default='planned', max_length=24)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='deliverystop',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='delivery.deliverytrip'),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, help_text='0=شنبه تا 6=جمعه', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='organization.branch')),
                ('sales_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_routes', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='organization.zone')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='GPSTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gps_tracks', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gps_tracks', to='delivery.route')),
            ],
        ),
        migrations.AddField(
            model_name='deliverytrip',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='delivery.route'),
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('planned_minutes', models.PositiveIntegerField(default=15)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_stops', to='sales.customer')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='delivery.route')),
            ],
            options={
                'ordering': ['route', 'sequence'],
                'unique_together': {('route', 'sequence')},
            },
        ),
        migrations.AddField(
            model_name='deliverytrip',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='delivery.vehicle'),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('planned', 'برنامه\u200cریزی\u200cشده'), ('in_progress', 'در حال انجام'), ('completed', 'انجام\u200cشده'), ('skipped', 'انجام\u200cنشده')], default='planned', max_length=16)),
                ('check_in_at', models.DateTimeField(blank=True, null=True)),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('check_in_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_in_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('route_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='delivery.routestop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
