# Generated by Django 5.1.15 on 2026-09-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_plan',
            field=models.JSONField(blank=True, default=dict, help_text='OSRM route plan: ordered stops, geometry, distance, duration and navigation steps'),
        ),
    ]
