# Generated by Django 5.1.15 on 2026-09-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending_approval', 'در انتظار تأیید'), ('approved', 'تأیید اعتبار'), ('reserved', 'رزرو شده'), ('confirmed', 'تأیید نهایی'), ('cancelled', 'باطل'), ('rejected', 'رد شده'), ('warehouse_pending', 'در انتظار انبار'), ('preparing', 'در حال آماده\u200cسازی'), ('ready_for_delivery', 'آماده ارسال'), ('out_for_delivery', 'در مسیر تحویل'), ('delivered', 'تحویل کامل'), ('partially_delivered', 'تحویل ناقص'), ('received', 'رسید ثبت شد'), ('returned', 'برگشت\u200cشده')], db_index=True, default='draft', max_length=24),
        ),
    ]
