name: Build Abtin Maps

on:
  workflow_dispatch:
    inputs:

      mode:
        description: "Build mode"
        required: true
        type: choice
        options:
          - all
          - custom
        default: custom

      countries:
        description: "Country codes (example: IR,DE,FR)"
        required: false
        default: ""

      force_rebuild:
        description: "Force rebuild existing maps"
        required: false
        type: boolean
        default: false


jobs:

  prepare:
    runs-on: ubuntu-latest

    outputs:
      countries: ${{ steps.prepare.outputs.countries }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Prepare country list
        id: prepare
        shell: bash
        run: |

          FORCE="${{ inputs.force_rebuild }}"
          MODE="${{ inputs.mode }}"
          INPUT="${{ inputs.countries }}"


          if [ "$MODE" = "all" ]; then

            COUNTRIES=$(cat tools/countries.txt)

          else

            COUNTRIES=$(echo "$INPUT" | tr ',' ' ')

          fi


          BUILD=""

          for C in $COUNTRIES
          do

            FILE="output/${C}.abm"


            if [ "$FORCE" = "true" ]; then

              BUILD="$BUILD $C"

            elif [ ! -f "$FILE" ]; then

              BUILD="$BUILD $C"

            else

              echo "Skip $C - already built"

            fi

          done


          JSON=$(echo $BUILD | tr ' ' '\n' | jq -R . | jq -s -c .)


          echo "countries=$JSON" >> $GITHUB_OUTPUT



  build:

    needs: prepare

    if: needs.prepare.outputs.countries != '[]'

    runs-on: ubuntu-latest


    strategy:

      fail-fast: false

      matrix:

        country: ${{ fromJson(needs.prepare.outputs.countries) }}



    steps:


      - name: Checkout
        uses: actions/checkout@v4



      - name: Build map

        run: |

          echo "Building ${{ matrix.country }}"


          python3 tools/abtinmap_build.py \
          ${{ matrix.country }}.osm.pbf \
          -o output/${{ matrix.country }}.abm \
          --region ${{ matrix.country }}



      - name: Save manifest

        run: |

          python3 tools/make_manifest.py
